PlatformaELearningowa.Web/Models/Entities/Topic.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlatformaELearningowa.Web.Models.Entities
{
    public class Topic
    {
		public int CourseId { get; set; }
		public virtual Course Course { get; set; }

		public int TopicId { get; set; }

		public int TopicNumber { get; set; }

		public string Name { get; set; }

		public string Description { get; set; }

		public virtual ICollection<File> Files { get; set; }
	}
}

PlatformaELearningowa.Web/Models/ViewModels/Topics/TopicDetailedVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PlatformaELearningowa.Web.Models.ViewModels.Common;

namespace PlatformaELearningowa.Web.Models.ViewModels.Topics
{
    public class TopicDetailedVM
	{
		public int CourseId { get; set; }

		public int TopicId { get; set; }

		public int TopicNumber { get; set; }

		public string Name { get; set; }

		public string Description { get; set; }

		public IEnumerable<FileVM> Files { get; set; }
	}
}

PlatformaELearningowa.Web/Models/ViewModels/Topics/TopicSimpleVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlatformaELearningowa.Web.Models.ViewModels.Topics
{
    public class TopicSimpleVM
	{
		public int CourseId { get; set; }

		public int? TopicId { get; set; }

		public int TopicNumber { get; set; }

		public string Name { get; set; }
	}
}

PlatformaELearningowa.Web/Models/ViewModels/Topics/TopicWriteVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace PlatformaELearningowa.Web.Models.ViewModels.Topics
{
    public class TopicWriteVM
    {
		public int CourseId { get; set; }

		public int? TopicId { get; set; }

		[Required(ErrorMessage = "Pole wymagane.")]
		public string Name { get; set; }

		[Required(ErrorMessage = "Pole wymagane.")]
		public string Description { get; set; }
	}
}

PlatformaELearningowa.Web/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PlatformaELearningowa.Web.Models.Entities;
using PlatformaELearningowa.Web.Services;
using MimeTypes.Core;
using System.ComponentModel.DataAnnotations;
using System.Net;
using PlatformaELearningowa.Web.Models.ViewModels.Courses;
using PlatformaELearningowa.Web.Models.ViewModels.Projects;

namespace PlatformaELearningowa.Web.Controllers
{
	[Authorize]
	public class FilesController : Controller
	{
		private readonly IFilesService filesService;
		private readonly UserManager<User> userManager;
		private readonly INotificationManager notificationManager;

		public FilesController(
			IFilesService filesService,
			UserManager<User> userManager,
			INotificationManager notificationManager)
		{
			this.filesService = filesService;
			this.userManager = userManager;
			this.notificationManager = notificationManager;
		}

		[HttpGet]
		public IActionResult CourseFileDownload(int fileId, int courseId)
		{
			IActionResult result = null;

			var userId = userManager.GetUserId(User);

			(byte[] file, string contentType)= filesService.GetCourseFile(fileId, courseId, userId);

			result = File(file, contentType, String
				.Format("{0}{1}","download", MimeTypeMap.GetExtension(contentType)));

			return result;
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult CourseFileUpload(CourseFileUploadVM uploadData)
		{
			if (!ModelState.IsValid)
			{
				Response.StatusCode = (int)HttpStatusCode.BadRequest;
				var errorMessages = ModelState.Values.SelectMany(m => m.Errors.Select(b => b.ErrorMessage));
				return Content(errorMessages.First());
			}
			var userId = userManager.GetUserId(User);

			filesService.AddCourseFile(uploadData.File, uploadData.CourseId, userId, uploadData.TopicId);

			return RedirectToAction("Details", "Courses", new { uploadData.CourseId });
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult FileDelete(int fileId)
		{
			var userId = userManager.GetUserId(User);

			filesService.DeleteFile(fileId, userId);
			(var content, var type) = notificationManager.GetLastNotification();

			if(notificationManager.CriticalErrorOccured || type == NotificationType.Error)
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;

			return Content(content);
		}



		[HttpGet]
		public IActionResult ProjectFileDownload(int projectId)
		{
			IActionResult result = null;

			var userId = userManager.GetUserId(User);

			(byte[] file, string contentType) = filesService.GetProjectFile(projectId, userId);

			result = File(file, contentType, String
				.Format("{0}{1}", "download", MimeTypeMap.GetExtension(contentType)));

			return result;
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult ProjectFileUpload(ProjectFileUploadVM uploadData)
		{
			if (!ModelState.IsValid)
			{
				Response.StatusCode = (int)HttpStatusCode.BadRequest;
				var errorMessages = ModelState.Values.SelectMany(m => m.Errors.Select(b => b.ErrorMessage));
				return Content(errorMessages.First());
			}
			var userId = userManager.GetUserId(User);

			filesService.AddProjectFile(uploadData.File, uploadData.ProjectId, userId);

			return RedirectToAction("StudentDetails", "Projects", new { uploadData.ProjectId });
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult ProjectFileDelete(int projectId)
		{
			var userId = userManager.GetUserId(User);

			filesService.DeleteProjectFile(projectId, userId);
			(var content, var type) = notificationManager.GetLastNotification();

			if (notificationManager.CriticalErrorOccured || type == NotificationType.Error)
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;

			return Content(content);
		}
	}
}

PlatformaELearningowa.Web/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PlatformaELearningowa.Web.Factories;
using PlatformaELearningowa.Web.Models.Entities;
using PlatformaELearningowa.Web.Models.ViewModels.Topics;
using PlatformaELearningowa.Web.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace PlatformaELearningowa.Web.Controllers
{
	[Authorize]
    public class TopicsController : Controller
    {
		private readonly ITopicsService topicsService;
		private readonly INotificationManager notificationManager;
		private readonly UserManager<User> userManager;
		private readonly ITopicsFactory topicsFactory;

		public TopicsController(ITopicsService topicsService,
			INotificationManager notificationManager,
			UserManager<User> userManager,
			ITopicsFactory topicsFactory)
		{

			this.topicsService = topicsService;
			this.notificationManager = notificationManager;
			this.topicsFactory = topicsFactory;
			this.userManager = userManager;
		}

        // GET: /<controller>/
		[HttpGet]
        public IActionResult Index(int courseId)
        {
			var topics = topicsService.GetCourseTopics(courseId);
            return View(topics);
        }

		[HttpGet]
		public IActionResult Details(int courseId, int topicId)
		{
			var topic = topicsService.GetTopicDetails(courseId, topicId);
			return View(topic);
		}

		[HttpGet]
		public IActionResult Form(int courseId, int? topicId)
		{
			TopicWriteVM topicVM = null;
			if(topicId != null)
			{
				topicVM = topicsService.GetTopicForEdition(courseId, (int)topicId);
			}
			else
			{
				topicVM = topicsFactory.CreateWriteViewModel(courseId);
				topicVM.CourseId = courseId;
			}
			return View(topicVM);
		}

		[HttpPost]
		public IActionResult Create(TopicWriteVM topic)
		{

			IActionResult result = null;
			if (ModelState.IsValid)
			{
				var userId = userManager.GetUserId(User);
				topicsService.AddNewTopic(topic);
				result = RedirectToAction("Details","Courses", new { topic.CourseId });
			}
			else
			{
				result = View("Form", topic);
			}
			return result;
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Update(TopicWriteVM topic)
		{
			IActionResult result = null;
			if (ModelState.IsValid)
			{
				topicsService.EditExisitngTopic(topic);
				result = RedirectToAction("Details", "Courses", new { topic.CourseId });
			}
			else
			{
				result = View("Form", topic);
			}
			return result;
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(int courseId, int topicId)
		{
			IActionResult result = null;
			var userId = userManager.GetUserId(User);
			topicsService.DeleteTopic(courseId, topicId);
			(var notificationContent, var notificationType) = notificationManager.GetLastNotification();
			if (notificationType == NotificationType.Error || notificationManager.CriticalErrorOccured)
			{
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;
			}
			result = Content(notificationContent);

			return result;
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult ChangeTopicNumber(int courseId, int topicId, int newNumber)
		{
			IActionResult result = null;
			topicsService.ChangeTopicNumber(courseId, topicId, newNumber);
			(string content, NotificationType type) = notificationManager.GetLastNotification();

			if(type == NotificationType.Error || notificationManager.CriticalErrorOccured)
			{
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;
			}
			result = Content(content);

			return result;
		}
	}
}

PlatformaELearningowa.Web/Views/Topics/Details.cshtml
@using PlatformaELearningowa.Web.Models.ViewModels.Courses
@using PlatformaELearningowa.Web.Models.ViewModels.Topics
@using PlatformaELearningowa.Web.Models.Entities
@using Microsoft.AspNetCore.Identity;

@model TopicDetailedVM
@{
    ViewData["Title"] = Model.Name;
}
<h2 class="row">@Html.Encode(Model.Name)</h2>
<div class="panel">
    <div class="row">
        @Model.Description
    </div>

    <hr />

    <div class="container mt-3">
        @if (User.IsInRole("Teacher"))
        {
        <form asp-action="CourseFileUpload" asp-controller="Files"
              method="post" class="row" enctype="multipart/form-data" id="file-upload-form">
            @Html.AntiForgeryToken()
            <input asp-for="CourseId" type="hidden" />
            <input asp-for="TopicId" type="hidden" />
            <div class="col-md-8">
                <div class="form-group">
                    <input name="file" id="file" type="file" class="filestyle"
                           data-text="Wybierz Plik" data-btnClass="btn-info" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <input type="button" class="btn btn-success" value="Dodaj Plik" onclick="uploadFile()" />
                </div>
            </div>
        </form>
        }
        @foreach (var file in Model.Files)
        {
            <div class="row mt-2" id="file-@file.FileId">
                <div class="col-md-8">
                    <a asp-action="CourseFileDownload" asp-controller="Files"
                       asp-route-courseId="@Model.CourseId"
                       asp-route-topicId="@Model.TopicId"
                       asp-route-fileId="@file.FileId">
                        <i class="fa fa-file"></i> @file.Name
                    </a>
                </div>
                <div class="col-md-4">
                    @if (User.IsInRole("Teacher"))
                    {
                    <form asp-action="FileDelete" asp-controller="Files" method="post"
                          id="file-delete-form-@file.FileId">
                        @Html.AntiForgeryToken()
                        <input name="fileId" value="@file.FileId" type="hidden" />
                        <button class="btn btn-danger" type="button"
                                onclick="deleteFile(@file.FileId)">
                            <i class="fa fa-trash"></i>
                        </button>
                   </form>
                   }
                </div>
            </div>
        }
    </div>
</div>
<hr />
@Html.ActionLink("Powrót na stronę kursu", "Details", "Courses", new { Model.CourseId })

@section Scripts {
    @if (User.IsInRole("Teacher"))
    {
    <script>
        let deleteFile = (fileId) => {
            let deletionForm = $('#file-delete-form-' + fileId);

            $.ajax({
                type: 'POST',
                url: deletionForm.prop('action'),
                data: deletionForm.serialize(),
            })
                .done((data, textStatus, jqXHR) => {
                    $.notify(data, 'success');
                    $('#file-' + fileId).hide();
                })
                .fail((jqXHR, textStatus, errorThrown) => {
                    $.notify(errorThrown, 'error');
                });
        };

        let uploadFile = () => {
            let uploadForm = $('#file-upload-form');
            let data = new FormData(uploadForm[0]);

            $.ajax({
                url: uploadForm.prop('action'),
                type: 'POST',
                enctype: 'multipart/form-data',
                cache: false,
                contentType: false,
                processData: false,
                data: data,
            })
                .done(() => {
                    location.reload(true);
                })
                .fail((jqXHR, textStatus, errorThrown) => {
                    $.notify(jqXHR.responseText, "error");
                });
        };
    </script>
    }
}

PlatformaELearningowa.Web/Views/Topics/Form.cshtml
@using PlatformaELearningowa.Web.Models.ViewModels.Topics
@model TopicWriteVM

@{
    var editionForm = Model?.TopicId != null;
    ViewData["Title"] = (editionForm ? "Edytuj" : "Stwórz") + "Temat";
}
<div class="border border-success rounded p-5 mt-5">
    <h2>@(editionForm ? "Edytuj " : "Stwórz") Temat</h2>
    <form asp-action="@(editionForm ? "Update" : "Create")" asp-controller="Topics"
          enctype="multipart/form-data" method="post">
        @Html.AntiForgeryToken()

        @if (editionForm)
        {
            <input asp-for="TopicId" type="hidden" />
        }
        <input asp-for="CourseId" type="hidden"/>

        <div class="form-group">
            <label asp-for="Name" class="col-form-label"></label>
            <input asp-for="Name" class="form-control" placeholder="" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="col-form-label"></label>
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Zatwierdź" class="btn btn-success" />
            <a class="btn btn-danger" href="@Url.Action("Index")">Anuluj</a>
        </div>

    </form>
</div>

PlatformaELearningowa.Web/Views/Topics/Index.cshtml
@using PlatformaELearningowa.Web.Models.ViewModels.Topics
@model IEnumerable<TopicSimpleVM>
@{ 
    Layout = null;
}

<div class="list-group">
    <div class="list-group-item text-center">
        <a asp-action="GetForm" class="btn btn-success">Nowy Temat</a>
    </div>
    @foreach (TopicSimpleVM t in Model)
    {
        <div class="list-group-item">
            <div class="container-fluid">
                <div class="row">
                    <div class="offset-md-3 col-md-6 text-center">
                        <a href="@Url.Action("Details", "Topics", new { topicId = t.TopicId })">
                            @t.Name
                        </a>
                    </div>
                    <div class="offset-md-1 col-md-1">
                        @if (User.IsInRole("Teacher"))
                        {
                        <a asp-action="GetForm" asp-controller="Topics" asp-route-topicId="@t.TopicId"
                           class="btn btn-info">
                            <i class="fa fa-pencil"></i>
                        </a>
                        }
                    </div>
                    <div class="col-md-1">
                        @if (User.IsInRole("Teacher"))
                        {
                        <form asp-action="Delete" asp-controller="Topics" asp-route-topicId="@t.TopicId">
                            @Html.AntiForgeryToken()
                            <input type="hidden" for="@t.CourseId" name="@t.CourseId" />
                            <button class="btn btn-danger" type="submit"
                                    value="Usuń" style="cursor:pointer; ">
                                <i class="fa fa-trash"></i>
                            </button>
                        </form>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>