PlatformaELearningowa.Web/Controllers/AnnouncementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlatformaELearningowa.Web.Models;
using PlatformaELearningowa.Web.Models.Entities;
using PlatformaELearningowa.Web.Models.ViewModels.Announcements;
using PlatformaELearningowa.Web.Models.ViewModels.Courses;

namespace PlatformaELearningowa.Web.Controllers
{
	[Authorize(Roles = "Teacher")]
    public class AnnouncementsController : Controller
    {
		private readonly IMapper mapper;
		private readonly ELearningContext db;

		public AnnouncementsController(ELearningContext db,
			IMapper mapper)
		{
			this.db = db;
			this.mapper = mapper;
		}

        public IActionResult Index()
		{
			IActionResult result = null;
			try
			{
				var dbAnnouncements = db.Announcements
					.Include(a => a.Course)
					.ToList();
				result = View(dbAnnouncements);
			}
			catch (Exception)
			{
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;
				throw;
			}
			return result;
		}

		public IActionResult Form(int? announcementId)
		{
			IActionResult result = null;
			try
			{
				var courses = mapper.Map<IEnumerable<CourseSimpleVM>>(db.Courses.ToList());
				AnnouncementWriteVM announcement = null;
				if(announcementId != null)
				{
					var dbAnnouncement = db.Announcements.FirstOrDefault(a => a.AnnouncementId == announcementId);
					announcement = mapper.Map<AnnouncementWriteVM>(dbAnnouncement);

				}
				else
				{
					announcement = new AnnouncementWriteVM();
				}
				announcement.AvailableCourses = courses;
				result = View(announcement);
			}
			catch (Exception)
			{
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;
				throw;
			}
			return result;
		}

		public IActionResult Write(AnnouncementWriteVM announcement)
		{
			IActionResult result = null;
			try
			{
				if(announcement.AnnouncementId != null)
				{
					var dbAnnouncement = db.Announcements.FirstOrDefault(a => a.AnnouncementId == announcement.AnnouncementId);
					dbAnnouncement.Content = announcement.Content;
					dbAnnouncement.CourseId = announcement.CourseId;
					dbAnnouncement.Title = announcement.Title;
					db.Attach(dbAnnouncement).State = EntityState.Modified;
				}
				else
				{
					var dbAnnouncement = mapper.Map<Announcement>(announcement);
					db.Attach(dbAnnouncement).State = EntityState.Added;
				}
				db.SaveChanges();
				result = RedirectToAction("Index");
			}
			catch (Exception)
			{
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;
				throw;
			}
			return result;
		}

		public IActionResult Delete(int announcementId)
		{
			IActionResult result = null;
			try
			{
				var toDelete = db.Announcements.FirstOrDefault(a => a.AnnouncementId == announcementId);
				db.Attach(toDelete).State = EntityState.Deleted;
				db.SaveChanges();
				result = Content("Ogłoszenie usunięte pomyslnie.");
			}
			catch (Exception)
			{
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;
				result = Content("Nie udało się usunąć ogłoszenia.");
				throw;
			}
			return result;
		}
	}
}

PlatformaELearningowa.Web/Controllers/CoursesController.cs
using System.Collections.Generic;
using System.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PlatformaELearningowa.Web.Services;
using PlatformaELearningowa.Web.Models.Entities;
using PlatformaELearningowa.Web.Factories;
using PlatformaELearningowa.Web.Models.ViewModels.Courses;

namespace PlatformaELearningowa.Web.Controllers
{
	[Authorize]
    public class CoursesController : Controller
    {
		private readonly ICoursesService coursesService;
		private readonly INotificationManager notificationManager;
		private readonly UserManager<User> userManager;
		private readonly ICoursesFactory coursesFactory;

		public CoursesController(
			ICoursesService coursesService,
			INotificationManager notificationManager,
			UserManager<User> userManager,
			ICoursesFactory coursesFactory)
		{
			this.coursesService = coursesService;
			this.notificationManager = notificationManager;
			this.userManager = userManager;
			this.coursesFactory = coursesFactory;
		}

		[HttpGet]
        public IActionResult Index(bool onlyAttended = false, int pageNumber = 1, int pageSize = 20)
        {
			IEnumerable<CourseSimpleVM> courses = null;
			if (onlyAttended)
			{
				var userId = userManager.GetUserId(User);
				courses = coursesService.GetAttendedCourses(pageNumber, pageSize, userId); 
			}
			else
			{
				courses = coursesService.GetCourses(pageNumber, pageSize);
			}
            return View(courses);
        }

		[HttpGet]
		public IActionResult Details(int courseId)
		{
			var userId = userManager.GetUserId(User);
			CourseDetailedVM course = coursesService.GetCourse(courseId, userId);
			IActionResult result = null;

			if(course != null)
			{
				result = View(course);
			}
			else
			{
				var enrollmentVM = coursesFactory.CreateCourseEnrollmentVM(courseId, null);
				result = View("EnrollmentForm", enrollmentVM);
			}
			return result;
		}

		[HttpGet]
		public IActionResult GetForm(int? courseId)
		{
			IActionResult result = null;

			if(courseId != null)
			{
				var userId = userManager.GetUserId(User);
				var course = coursesService.GetCourseForEditing((int)courseId, userId);

				if(course == null)
				{
					var enrollmentVM = coursesFactory
						.CreateCourseEnrollmentVM((int)courseId, null);
					result = View("EnrollmentForm", enrollmentVM);
				}
				else
				{
					result = View("Form", course);
				}
			}
			else
			{
				result = View("Form", null);
			}

			return result;
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(CourseWriteVM course)
		{
			IActionResult result = null;
			if (ModelState.IsValid)
			{
				var userId = userManager.GetUserId(User);
				course.CreatorId = userId;
				coursesService.AddCourse(course);
				result = RedirectToAction("Index");
			}
			else
			{
				result = View("Form", course);
			}
			return result;
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Update(CourseWriteVM course)
		{
			IActionResult result = null;
			if (ModelState.IsValid)
			{
				coursesService.EditCourse(course);
				result = RedirectToAction("Index");
			}
			else
			{
				result = View("Form", course);
			}
			return result;
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(int courseId)
		{
			var userId = userManager.GetUserId(User);
			coursesService.RemoveCourse(courseId, userId);
			(var notificationContent, var notificationType) = notificationManager.GetLastNotification();
			if (notificationType == NotificationType.Error || notificationManager.CriticalErrorOccured)
			{
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;
			}

			return RedirectToAction("Index");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Enroll(CourseEnrollmentVM model)
		{
			if (!ModelState.IsValid)
			{
				return View("EnrollmentForm", model);
			}

			IActionResult result = null;
			var userId = userManager.GetUserId(User);
			coursesService.EnrollToCourse(model.EnrollmentKey, userId, model.CourseId);
			(var notificationContent, var notificationType) = notificationManager.GetLastNotification();

			if (notificationType == NotificationType.Error || notificationManager.CriticalErrorOccured)
			{
				ModelState.AddModelError("EnrollmentKey", notificationContent);
				result = View("EnrollmentForm", model);
			}
			else
			{
				result = RedirectToAction("Details", new { courseId = model.CourseId });
			}

			return result;
		}
	}
}

PlatformaELearningowa.Web/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlatformaELearningowa.Web.Models;
using PlatformaELearningowa.Web.Models.Entities;
using PlatformaELearningowa.Web.Models.ViewModels.Projects;
using System.Net;
using Microsoft.EntityFrameworkCore;
using PlatformaELearningowa.Web.Models.ViewModels.Courses;

namespace PlatformaELearningowa.Web.Controllers
{
	[Authorize]
    public class ProjectsController : Controller
    {
		private readonly ELearningContext db;
		private readonly IMapper mapper;
		private readonly UserManager<User> userManager;

		public ProjectsController(IMapper mapper,
			ELearningContext db,
			UserManager<User> userManager)
		{
			this.db = db;
			this.mapper = mapper;
			this.userManager = userManager;
		}

		[Authorize(Roles = "Student")]
		public IActionResult Index()
		{
			IActionResult result = null;
			try
			{
				var userId = userManager.GetUserId(User);
				var dbProjects = db.Projects
					.Where(p => p.StudentId.Equals(userId))
					.Include(p => p.Course)
					.ToList();
				var projects = mapper.Map<IEnumerable<ProjectSimpleVM>>(dbProjects);
				result = View(projects);
			}
			catch (Exception)
			{
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;
				throw;
			}
			return result;
		}

		[Authorize(Roles = "Student")]
		public IActionResult StudentDetails(int projectId)
		{
			IActionResult result = null;
			try
			{
				var dbProject = db.Projects
					.Include(p => p.File)
					.Include(p => p.Course)
					.First(p => p.ProjectId == (int)projectId);
				var project = mapper.Map<ProjectStudentVM>(dbProject);
				result = View(project);
			}
			catch (Exception)
			{
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;
				throw;
			}
			return result;
		}

		[Authorize(Roles = "Teacher")]
		public IActionResult TeacherDetails(int? projectId = null, string studentId = null)
		{
			IActionResult result = null;
			try
			{
				var availabeDbCourses = db.Courses;
				if(projectId != null)
				{
					ViewBag.NewProject = false;
					var dbProject = db.Projects
						.Include(p => p.File)
						.First(p => p.ProjectId == (int)projectId);
					var project = mapper.Map<ProjectTeacherVM>(dbProject);
					project.AvailableCourses = mapper.Map<List<CourseSimpleVM>>(availabeDbCourses.ToList());
					result = View(project);
				}
				else if (!String.IsNullOrWhiteSpace(studentId))
				{
					ViewBag.NewProject = true;
					var newProject = new ProjectTeacherVM {
						StudentId = studentId,
						AvailableCourses = mapper.Map<List<CourseSimpleVM>>(availabeDbCourses.ToList())
					};
					result = View(newProject);
				}
				else
				{
					Response.StatusCode = (int)HttpStatusCode.BadRequest;
				}
			}
			catch (Exception)
			{
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;
				throw;
			}
			return result;
		}

		[Authorize(Roles = "Teacher")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Write(ProjectTeacherVM model)
		{
			IActionResult result = null;
			try
			{
				if(model.ProjectId == null)
				{
					var dbProject = mapper.Map<Project>(model);
					db.Entry<Project>(dbProject).State = EntityState.Added;
				}
				else
				{
					var dbProject = db.Projects
						.FirstOrDefault(p => p.ProjectId == model.ProjectId);
					mapper.Map<ProjectTeacherVM, Project>(model, dbProject);
					db.Entry<Project>(dbProject).State = EntityState.Modified;
				}
				db.SaveChanges();
				result = RedirectToAction("Form", "Students", new { studentId = model.StudentId });
			}
			catch (Exception)
			{
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;
				throw;
			}
			return result;
		}

		[Authorize(Roles = "Teacher")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(int projectId)
		{
			IActionResult result = null;
			try
			{
				var toDelete = db.Projects.FirstOrDefault(p => p.ProjectId == projectId);
				db.Entry<Project>(toDelete).State = EntityState.Deleted;
				db.SaveChanges();
				result = Content("Projekt usunięty pomyślnie.");
			}
			catch (Exception)
			{
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;
				result = Content("Usuwanie projektu nie powiodło się.");
				throw;
			}
			return result;
		}
	}
}

PlatformaELearningowa.Web/Views/Shared/_FileList.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

PlatformaELearningowa.Web/Views/Shared/_Head.cshtml
@model string
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - @Model</title>

<environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/dist/css/font-awesome.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/dist/css/font-awesome.min.css" />
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</environment>

PlatformaELearningowa.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@{ string applicationName = "Platforma E-Learningowa"; }
<html>
<head>
    @{ Html.RenderPartial("_Head", applicationName); }
</head>
<body>
    <div class="container">
        @{ Html.RenderPartial("_Navbar", applicationName); }
        <div class="mt-5">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; 2017 - @applicationName</p>
        </footer>
    </div>
    @{ Html.RenderPartial("_Scripts"); }
    @RenderSection("Scripts", required: false)
</body>
</html>

PlatformaELearningowa.Web/Views/Shared/_Navbar.cshtml
@model string
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
    <div class="container-fluid">
        <a href="@Url.Action("Index","Home")" class="navbar-brand">
            <img src="~/images/logo.png" class="logo" />
            <span class="navbar-brand">@Model</span>
        </a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarResponsive" style="">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href='@Url.Action("Index", "Courses")'>
                        Dostępne Kursy
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href='@Url.Action("Index", "Courses", new { onlyAttended = true })'>
                        Moje Kursy
                    </a>
                </li>
                @if (User.IsInRole("Teacher"))
                {
                    <li class="nav-item">
                        <a class="nav-link" href='@Url.Action("Index", "Students")'>
                            Studenci
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href='@Url.Action("Index", "Groups")'>
                            Grupy
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href='@Url.Action("Index", "Announcements")'>
                            Ogłoszenia
                        </a>
                    </li>
                }
                else if (User.IsInRole("Student"))
                {
                    <li class="nav-item">
                        <a class="nav-link" href='@Url.Action("Index", "Projects")'>
                            Moje Projekty
                        </a>
                    </li>
                }
                @await Html.PartialAsync("_LoginPartial")
            </ul>
        </div>
    </div>
</nav>

PlatformaELearningowa.Web/Views/Shared/_ProjectsList.cshtml
@using PlatformaELearningowa.Web.Models.ViewModels.Projects
@model IEnumerable<ProjectSimpleVM>
@{
    Layout = null;
}
<div class="list-group mt-3">
    @foreach (var p in Model)
    {
        <div class="list-group-item" id="project-@p.ProjectId">
            <div class="container">
                <div class="row">
                    <div class="offset-md-2 col-md-8 text-center">
                        @Html.ActionLink(p.Course.Name + " - " + p.Title, User.IsInRole("Student") ? "StudentDetails" : "TeacherDetails", "Projects",
                            new { projectId = p.ProjectId })
                    </div>
                    <div class="offset-md-1 col-md-1">
                        @if (User.IsInRole("Teacher"))
                        {
                            <form asp-controller="Projects" asp-action="Delete" id="project-deletion-form-@p.ProjectId" method="post">
                                @Html.AntiForgeryToken()
                                <input type="hidden" value="@p.ProjectId" name="projectId" />
                                <button onclick="deleteProject(@p.ProjectId);" class="btn btn-danger" type="button">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </form>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<script>
    function deleteProject(projectId) {
        let form = $('#project-deletion-form-' + projectId);
        let project = $('#project-' + projectId);
        console.log(form.serialize());
        $.ajax({
            url: form.prop('action'),
            data: form.serialize(),
            type: 'POST',
            success: function (data) {
                $.notify(data, 'success');
                project.remove();
            },
            error: function (jqXHR) {
                $.notify(jqXHR.responseText, 'error');
            }
        })
    }
</script>

PlatformaELearningowa.Web/Views/Shared/_Scripts.cshtml
<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/popper/dist/umd/popper.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/notify/dist/notify.js"></script>
    <script src="~/lib/bootstrap-filestyle/dist/bootstrap-filestyle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/popper/dist/umd/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/notify/dist/notify.min.js"></script>
    <script src="~/lib/bootstrap-filestyle/dist/bootstrap-filestyle.min.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>
<script>
</script>

PlatformaELearningowa.Web/Views/Shared/_SimpleLayout.cshtml
<!DOCTYPE html>
@{ string applicationName = "Platforma E-Learningowa"; }
<html>
<head>
    @{Html.RenderPartial("_Head", applicationName);}
</head>
<body>
    <div class="container">
        @RenderBody()
    </div>
    @{Html.RenderPartial("_Scripts");}
    @RenderSection("Scripts", required: false)
</body>
</html>